services:
    nextgen.phpbbdirectory.cron.task.core.prune_categorie:
        class: nextgen\phpbbdirectory\cron\task\core\prune_categorie
        arguments:
            - '@config'
            - '@nextgen.phpbbdirectory.core.cron'
        calls:
            - [set_name, [nextgen.phpbbdirectory.cron.task.core.prune_categorie]]
        tags:
            - { name: cron.task }